---
# handlers file for Myatu.shorewall

- name: enable shorewall
  service: name={{ shorewall_service_name }} enabled=yes

- name: enable shorewall6 
  service: name={{ shorewall6_service_name }} enabled=yes

- name: restart shorewall
  service: name={{ shorewall_service_name }} state=restarted

- name: restart shorewall6
  service: name={{ shorewall6_service_name }} state=restarted